Repository MON-DA-Y/BE, pull requests merged in 2025-09, with the labels that each got.

#54 Feat/#50/MySQL ↔ MongoDB 동기화
  app.js
  package.json
  src/app.js
  src/config/mysql.js
  src/controllers/monNewsController.js
  src/controllers/syncController.js
  src/cron/dailyNewsCron.js
  src/models/daily/dailyNews.js
  src/models/monNews.js
  src/routes/monNewsRouter.js
  src/routes/syncRouter.js
  src/scripts/syncDaily.js
  src/server.js
  src/services/syncService.js
  src/utils/date.js
Labels: MySQL ↔ MongoDB 동기화, 💰 동은

#55 Feat/#53/weakness API에 summary 추가 및 오류 수정
  src/controllers/progressController.js
  src/controllers/studentInfoController.js
  src/controllers/weaknessController.js
  src/models/weakness.js
  src/routes/studentInfoRouter.js
Labels: dummy API, 💰 혜원

#58 Feat/#50/JWT 토근 검증 로직 개선 (Auth.js)
  src/utils/auth.js
Labels: MySQL ↔ MongoDB 동기화, 💰 동은

#64 Feat/#61/monWord DB 동기화 및 연결 API 구현
  src/controllers/monNewsController.js
  src/controllers/monWordController.js
  src/controllers/studentMainController.js
  src/controllers/syncController.js
  src/cron/dailyCron.js
  src/cron/dailyNewsCron.js
  src/models/daily/dailyWord.js
  src/models/studentNews.js
  src/models/studentWord.js
  src/routes/monNewsRouter.js
  src/routes/monwordRouter.js
  src/routes/syncRouter.js
  src/server.js
  src/services/syncService.js
Labels: MySQL ↔ MongoDB 동기화, 💰 동은

#66 Feat/#61/monWord DB 연결 API 로직 수정
  src/controllers/monWordController.js
  src/controllers/newsHistoryController.js
  src/controllers/studentMainController.js
Labels: DB API, 💰 동은

#68 Feat/67/monQuiz DB 동기화 및 연결 API 구현
  src/controllers/monQuizController.js
  src/controllers/syncController.js
  src/cron/dailyCron.js
  src/models/daily/dailyQuiz.js
  src/models/studentQuiz.js
  src/routes/monQuizRouter.js
  src/routes/syncRouter.js
  src/services/syncService.js
Labels: MySQL ↔ MongoDB 동기화, DB API, 💰 동은

#70 Fix/#46,#61,#67/monQuiz, monWord, monNews level 오류 해결
  package.json
  src/controllers/monNewsController.js
  src/controllers/monQuizController.js
  src/controllers/monWordController.js
  src/controllers/studentInfoController.js
  src/models/daily/dailyNews.js
  src/models/daily/dailyWord.js
  src/models/studentQuiz.js
  src/models/studentWord.js
  src/utils/level.js
Labels: Fix, 💰 동은

#71 Feat/67/monQuiz DB 연결 API 구현
  src/controllers/monNewsController.js
  src/controllers/monQuizController.js
  src/controllers/monWordController.js
  src/models/daily/dailyQuiz.js
  src/models/studentQuiz.js
  src/routes/monQuizRouter.js
  src/services/syncService.js
Labels: DB API, 💰 동은

#77 feat/#42: 오늘의 학습률 - 시리즈 구현 완료
  src/controllers/studentMainController.js
Labels: DB API, 💰 동은
